---
# handlers file for ansible-role-fluentbit

- name: Restart Fluentbit
  service:
    name: td-agent-bit
    enabled: true
    state: restarted
  become: true

- name: Restart Osquery
  service:
    name: osqueryd
    enabled: true
    state: restarted
  become: true
