---
- name: Configure | Source td-agent-bit main conf
  template:
    src: td-agent-bit.conf
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: 0644
- name: Configure | Source osquery main conf
  template:
    src: osquery.conf
    dest: /etc/osquery/osquery.conf
    mode: 0644
  notify: Restart Osquery service
- name: Copy Shell script
  template:
    src: vm_info_extract.sh
    dest: /home/opc/vm_info_extract.sh
    mode: 777
- name: Update the OCI_metadata info and restart td-agent-bit and osquery
  shell: |
    /home/opc/vm_info_extract.sh
    sleep 10
    systemctl restart osqueryd.service
    systemctl restart td-agent-bit.service
    systemctl restart rsyslog.service