---
- name: Write VM metadata to var log vm info
  shell: |
    oci-metadata -j > /var/log/vminfo
    if [ -e /etc/yum.repos.d/oracle-linux-ol7.repo.osms-backup ]
    then
        mv /etc/yum.repos.d/oracle-linux-ol7.repo.osms-backup /etc/yum.repos.d/oracle-linux-ol7.repo
    else
        echo "File Doesn't exist"
    fi

- name: Install Redhat | Add yum repository
  yum_repository:
    name: TD_Agent_Bit
    baseurl: http://packages.fluentbit.io/centos/7/$basearch/
    gpgcheck: 1
    gpgkey: http://packages.fluentbit.io/fluentbit.key
    description: Fluent bit repo
    enabled: 1

- name: Install Osquery
  include_tasks: 'osquery.yml'
