---
# tasks file for ansible-role-fluentbit
- name: Install jq
  environment:
    http_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
    https_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
  yum:
    name: "jq"
    state: present
    update_cache: yes
- name: Install Fluentbit
  include_tasks: 'install-{{ ansible_os_family }}.yml'
  tags: ['install']

- name: Download td agent-bit.rpm
  environment:
    http_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
    https_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
  get_url:
    url: https://packages.fluentbit.io/centos/7/x86_64/td-agent-bit-1.7.9-1.x86_64.rpm
    dest: /tmp/td-agent-bit-1.7.9-1.x86_64.rpm
    validate_certs: no
- name: Install td-agent-bit.rpm
  environment:
    http_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
    https_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
  yum:
    #name: https://packages.fluentbit.io/centos/7/x86_64/td-agent-bit-1.7.9-1.x86_64.rpm
    name: /tmp/td-agent-bit-1.7.9-1.x86_64.rpm
    state: present
- name: Download osquery rpm
  environment:
    http_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
    https_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
  get_url:
    url: https://pkg.osquery.io/rpm/osquery-4.9.0-1.linux.x86_64.rpm
    dest: /tmp/osquery-4.9.0-1.linux.x86_64.rpm
- name: Ensure latest version of packages is installed.
  environment:
    http_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
    https_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
  yum:
    name: /tmp/osquery-4.9.0-1.linux.x86_64.rpm
    state: present
- name: Ensure td-agent-bit Service is enabled and started
  become: true
  service:
    name: td-agent-bit
    enabled: yes 
    state: started
  notify: Restart Fluentbit service
- name: Ensure osquery Service is enabled and started Osquery
  become: true
  service:
    name: osqueryd
    enabled: yes
    state: started
  notify: Restart Osquery service
  
- import_tasks: configure.yml
