---
# tasks file for secInsight_6.x
- debug:
     msg: "OS_FAMILY: {{ ansible_os_family }}" 

- block:
  - include_tasks: osquery.yml
  - include_tasks: filebeat.yml
when: ansible_distribution_major_version == "6"
 


