# osquery Installation and Configuration for redhat distribution
 
- name: Install & configure Osquery
  become: yes
  block:
  - name: Install Osquery
    environment:
      http_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
      https_proxy: http://proxy-1.proxy.oal.oraclevcn.com:80
    yum:
      name: "https://osquery-packages.s3.us-east-1.amazonaws.com/rpm/osquery-{{osquery_version | default('4.9.0')}}-1.linux.x86_64.rpm"
      state: present
      validate_certs: no

  - name: Copy osquery.conf file to /etc/osquery/osquery.conf
    copy:
      src: osquery.conf
      dest: /etc/osquery
      owner: root
      group: root
      mode: 0644
    notify: Restart osquery

  - name: Make sure osquery autostarts
    service:
      name: osqueryd
      enabled: yes
  when: ansible_os_family == 'RedHat'

# We can add tasks for other OS distributions here.