---

- name: test play
  hosts: all
  become: yes
  vars:
    osquery_version: "4.9.0"
    filebeat_version: "7.17.0"
  tasks:
  - name: cleanup Osquery 
    ansible.builtin.yum:
      name: osqueryd
      state: absent
      validate_certs: no

  - name: Remove file Osquery conf file
    ansible.builtin.file:
      path: /etc/osquery   
      state: absent

  - name: Install filebeat 
    ansible.builtin.yum:
      name: filebeat
      state: absent
      validate_certs: no
  
  - name: Remove file Osquery conf file
    ansible.builtin.file:
      path: /etc/filebeat/ 
      state: absent

  - name: Install jq
    yum:
      name: jq
      state: absent
      update_cache: yes

  - name: remove td-agent-bit.rpm
    yum:  
      name: td-agent-bit
      state: absent
      disable_gpg_check: yes

  - name: Remove file Osquery conf file
    ansible.builtin.file:
      path: /etc/td-agent-bit/
      state: absent  
  
 

  
    