---
- hosts: all
  become: yes
  tasks:
  - include_role:
      name: ansible-role-fluentbit
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  - include_role:
      name: secInsight_6.x
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '7'
